// AUTO-GENERATED by wificities CLI — do not edit manually
// This file is regenerated when plugins are added/removed.
#ifndef PLUGIN_REGISTRY_H
#define PLUGIN_REGISTRY_H

#include "plugin_api.h"

// No backend plugins installed.

static WifiCitiesPlugin* registered_plugins[] = {};
static const int PLUGIN_COUNT = 0;

#endif // PLUGIN_REGISTRY_H
